### ISSUE TITLE
On Hold Power Automate 

### ISSUE THREAD

**Issue by TimCadieux** [ised-isde-canada/Buro#1]
As indicated in the documentation we request access to the Automate flow to clear "ON HOLD" reservations. We are noticing several on-hold reservations show up in our reports. Not sure why these reservations do not get deleted by themselves.

If someone could share plz.

**Comment by ianwilk20** [comment]
Hello @TimCadieux, we've recently added a new setup guide, [setup-manual.md](https://github.com/ised-isde-canada/Buro/blob/main/setup-manual.md); included in this guide is a step-wise description of how to set up the PowerAutomate flow for clearing ON HOLD reservations.

Hope this helps!
